SELECT 
EAN AS ISBN ,
FORMAT,
EBOOK_ISBN ,
FULL_TITLE AS TITLE,
TITLEPREFIXANDTITLE AS TITLE_PREFIX,
SUBTITLE ,
SERIES_NAME AS SERIES ,
US_PRICE ,
CANADIAN_PRICE ,
UK_PRICE,
AUTHOR_1 AS AUTHOR , 
TESTIMPRINTFROMHNA AS IMPRINT ,
BISAC1_DESC as BISAC_DESCRIPTION ,
SEASON,
BISAC_STATUS ,
ORIGIN,
EDITOR ,
MANAGING_EDITOR , 
PARENT_ISBN ,
 PUB_DATE ,
WAREHOUSE_DATE , 
RELEASE_DATE ,
GROUP_1 AS DIVISION ,
LICENSED ,
LICENSOR
FROM `abrams-books-403613.BUSINESS_INTELLIGENCE_LAYER_PROD.BIL_BOOKATTRIBUTES`
WHERE 
EAN IS NOT NULL 
  AND EAN <> '' 
  AND TRIM(EAN) <> ''
  AND EAN NOT LIKE 'EISBN%'
 -- AND GROUP_3 IN ('Magic Cat') 
# use GROUP_3 for RLS test on the values in the bracket.
