SELECT EAN as ISBN, 
  FULL_TITLE AS BOOK_TITLE,
  AUTHOR_1 AS AUTHOR,
  FORMAT ,
  TESTIMPRINTFROMHNA AS IMPRINT ,
  PUB_DATE ,
  RELEASE_DATE ,
  BISAC1_DESC AS BISAC_DESCRIPTION,
  US_PRICE,
  BISAC_STATUS ,
  SEASON,
  PARENT_ISBN
FROM `BUSINESS_INTELLIGENCE_LAYER_PROD.BIL_BOOKATTRIBUTES` WHERE EAN = ''
AND GROUP_3 ='Magic Cat'

-- Use Group_3 value as the RLS used .
